version: '3.1'
services:
  db:
    image: postgres:12.2
    container_name: hackathon
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
  storage:
    image: openresty/openresty
    container_name: hackathon-storage
    ports:
      - "${STORAGEPORT}:80"
    volumes:
      - "./server/s3/nginx.conf:/etc/openresty/nginx.conf"
      - "./server/s3/lua:/usr/local/openresty/nginx/conf/lua"
      - "./server/s3/data:/var/data:rw"
