version: '3.1'
services:
  db:
    image: postgres:12.2
    container_name: hackathon
    ports:
      - "${PGPORT}:5432"
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    environment:
      POSTGRES_USER: "${PGUSER}"
      POSTGRES_PASSWORD: "${PGPASSWORD}"
      POSTGRES_DB: "${PGDATABASE}"
